---
name: EC2 Staging-Server Deployment Workflow
on:
  push:
    branches:
      - master
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Verify Node.js Installation
        run: node --version
      - name: Install Dependencies
        run: |
          cd react_app
          npm install
      - name: Build Project
        run: |
          cd react_app
          npm run build-react
      - name: Test Project
        run: |
          cd react_app
          npm run test-react
      - name: Lint Codebase
        run: |
          cd react_app
          npx eslint src/sum.js src/cartview.js src/shippingOptions.js
      - name: Deployment onto the Staging Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/
          remote_host: ${{ secrets.IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}
      - name: Install Node Modules on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd react_app
            npm install
      - name: Notify on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: GitHub Action Success
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}
          body: |
            Workflow of ${{ github.repository }} initiated by ${{ github.actor }} was successfully executed.
            View the changes on the server http://${{ secrets.IP }}/

      - name: Notify on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: GitHub Action Failure
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}
          body: |
            Workflow of ${{ github.repository }} initiated by ${{ github.actor }} failed,
            kindly check the workflow logs!
